service: audit-function

configValidationMode: error

plugins:
  - serverless-offline

provider:
  iamRoleStatements:
    - Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Effect: Allow
      Resource: '*'
  memorySize: 128
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev
  versionFunctions: false

functions:
  hello:
    handler: src/main.handler